config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :admins
  resources :enrolls do
    get "studentenroll"
  end
  resources :instructors
  resources :students do
    get "test"
  end
  resources :courses do
    get "wait"
    get "waitremove"
  end
  resources :users
  root 'home#index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "users#signup", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
end

app/models/student.rb
class StudentValidator<ActiveModel::Validator
  def validate(record)
    email_regex = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    record.errors.add :base, "invalid Student email format" unless record.email.match(email_regex)
  end
end

class Student < ApplicationRecord
  has_secure_password
  has_many :enrolls, dependent: :destroy
  has_many :waitlists, dependent: :destroy
  validates :Name, :presence => true
  validates :email, :presence => true
  validates :password_digest, :presence => true
  validates :date_of_birth, :presence => true
  validates :Phone_Number, :presence => true, length: {is:10}
  validates :Major, :presence => true
  validates :Student_ID, :presence => true
  validates_with StudentValidator

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @Courses = Course.all
    @students = Student.all
    if current_user.user_type != "student"
      @students = Enroll.where(course_id:params[:course_id])
      @cid = params[:course_id]
    end

  end

  def wait
  end

  def test
    if current_user.user_type != "student"
      @students = Enroll.where(course_id:params[:course_id])
      @cid = params[:course_id]
      e = Enroll.where(course_id: params[:course_id], student_id: params[:student_id]).pluck(:id)
      Enroll.delete(e)
      @course = Course.find(params[:course_id])
      if @course.Capacity == 0 and @course.Waitlist_Capacity > 0
        @course.Waitlist_Capacity = @course.Waitlist_Capacity + 1
      else
        @course.Capacity = @course.Capacity + 1
      end
      @course.save
      

      
    end
    
  end


  # GET /students/1 or /students/1.json
  def show
    if !current_user.user_type.eql?("admin")
      respond_to do |format|
        format.html { redirect_to root_url, notice: "Unauthorized access" }
      end
    end
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    if !current_user.user_type.eql?("admin")
      respond_to do |format|
        format.html { redirect_to root_url, notice: "Unauthorized access" }
      end
    end
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)
    user_params = { "user_type" => "student", "email" => student_params["email"],
                    "password" => student_params["password"],
                    "password_confirmation" => student_params["password_confirmation"]}
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save && @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    if !current_user.user_type.eql?("admin")
      respond_to do |format|
        format.html { redirect_to root_url, notice: "Unauthorized access" }
      end
    else
      @user = User.where(:email => student_params[:email])[0]
      user_params = { "user_type" => "student", "email" => student_params["email"],
                      "password" => student_params["password"],
                      "password_confirmation" => student_params["password_confirmation"]}
      respond_to do |format|
        if @user.update(user_params) && @student.update(student_params)
          format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
          format.json { render :show, status: :ok, location: @student }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    if !current_user.user_type.eql?("admin")
      respond_to do |format|
        format.html { redirect_to root_url, notice: "Unauthorized access" }
      end
    else
      @user = User.where(:email => @student[:email])[0]
      @user.destroy
      @student.destroy

      respond_to do |format|
        if current_user.user_type.eql?("admin")
          format.html { redirect_to root_url, notice: "Student was successfully destroyed." }
          format.json { head :no_content }
        else
          format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
          format.json { head :no_content }
        end
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def student_params
    params.require(:student).permit(:Name, :date_of_birth, :Phone_Number, :Major, :Student_ID, :email, :password, :password_confirmation)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Name, style: "display: block" %>
    <%= form.text_field :Name %>
  </div>

  <div>
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.date_field :date_of_birth %>
  </div>

  <div>
    <%= form.label :Phone_Number, style: "display: block" %>
    <%= form.number_field :Phone_Number %>
  </div>

  <div>
    <%= form.label :Major, style: "display: block" %>
    <%= form.text_field :Major %>
  </div>

  <div>
    <%= form.label :Student_ID, style: "display: block" %>
    <%= form.text_field :Student_ID %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>
  <br>

  <div>
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.Name %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= student.date_of_birth %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= student.Phone_Number %>
  </p>

  <p>
    <strong>Major:</strong>
    <%= student.Major %>
  </p>

  <p>
    <strong>Student id:</strong>
    <%= student.Student_ID %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student.email %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student, {:class => "link-dark"} %> |
  <%= link_to "Back to students", students_path, {:class => "link-dark"} %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<!--<div id="students">-->
  <%# @students.each do |student| %>
    <%# if current_user.user_type != "instructor" %>
      <%#= render student %>
<!--      <p>-->
        <%#= link_to "Show this student", student, {:class => "link-dark"} %>
<!--      </p>-->
    <%# end %>
  <%# end %>

<!--</div>-->

<div>
  <% if current_user.user_type != "student" %>
    <p> Enrolled Students </p>
    <table class="table table-hover table-sm table-bordered table-striped">
      <thead class="table-dark">
      <tr>
        <th scope="col">Email</th>
        <th scope="col">Remove</th>
      </tr>
      </thead>
      <tbody>
      <% @students.each do |stu| %>
        <tr>
          <%= link_to student_path(stu.student_id, :course_id => @cid) do %>
            <td><%= Student.where(:id => stu.student_id).pluck(:email).first %></td>
            <td><%= link_to "Remove", student_test_path(:student_id => stu.student_id, :course_id => @cid) %></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>

</div>

app/views/students/new.html.erb
<p id="notice"><%= notice %></p>
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <% if current_user.nil?  %>
    <%= link_to "Back to SignUp", signup_path, {:class => "link-dark"} %>
  <%elsif !current_user.nil? && current_user.user_type == "admin" %>
    <%= link_to "Back to Home",  root_path, {:class => "link-dark"} %>
  <%end %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %><p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <% if current_user.user_type == "student" %>
  <%else %>
    <div class="flex-box">
      <%= link_to "Edit this student", edit_student_path(@student), class: "btn btn-secondary" %> &nbsp;&nbsp;
      <%= button_to "Destroy this student", @student, method: :delete, class: "btn btn-secondary" %>
    </div>
  <%end %>
  <br><br>
  <% if current_user.user_type == "admin" %>
    <%= link_to "Back to Home", root_path, {:class => "link-dark"} %><br>
  <%else %>
    <%= link_to "Back to students", students_path, {:class => "link-dark"} %>
  <%end %>
</div>

app/views/students/test.html.erb
<br></br>
<h1> Students </h1>

<div>
<% if current_user.user_type != "student" %>
<p> Enrolled Students </p>
  <table class="table table-hover table-sm table-bordered table-striped">
  <thead class="table-dark">
    <tr>
      <th scope="col">Email</th>
      <th scope="col">Remove</th>
    </tr>
    </thead>
    <tbody>
    <% @students.each do |stu| %>
        <tr>
          <%= link_to student_path(stu.student_id, :course_id => @cid) do %>
            <td><%= Student.where(:id => stu.student_id).pluck(:email).first %></td>
            <td><%= link_to "Remove", student_test_path(:student_id => stu.student_id, :course_id => @cid) %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
    </table>
  
<% end %>

</div>