config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :admins
  resources :enrolls do
    get "studentenroll"
  end
  resources :instructors
  resources :students do
    get "test"
  end
  resources :courses do
    get "wait"
    get "waitremove"
  end
  resources :users
  root 'home#index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "users#signup", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :signup]
  before_action :set_user, only: %i[ show edit update destroy ]

  #GET /signup
  def signup
  end

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:user_type, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.date_field :date_of_birth %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.label :user_type, style: "display: block" %>
    <%= form.select(:user_type, options_for_select([%w[Student student], %w[Instructor instructor], %w[Admin admin]])) %>
  </div>

  <div>
    <%= form.label :major, style: "display: block" %>
    <%= form.text_field :major %>
  </div>

  <div>
    <%= form.label :department, style: "display: block" %>
    <%= form.text_field :department %>
  </div>
  <br>
  <div>
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= user.date_of_birth %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= user.phone_number %>
  </p>

  <p>
    <strong>Major:</strong>
    <%= user.major %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= user.department %>
  </p>

  <p>
    <strong>User type:</strong>
    <%= user.user_type %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user, {:class => "link-dark"} %> |
  <%= link_to "Back to users", users_path, {:class => "link-dark"} %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user, {:class => "link-dark"} %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path, {:class => "link-dark"} %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path, {:class => "link-dark"} %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user), {:class => "link-dark"} %> |
  <%= link_to "Back to users", users_path, {:class => "link-dark"} %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/users/signup.html.erb
<p id="notice"><%= notice %></p>
<h1>Sign Up Portal</h1>
<%= link_to "Student SignUp", new_student_path, {:class => "link-dark"} %> or
<%= link_to "Instructor SignUp", new_instructor_path, {:class => "link-dark"} %><br>