config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :admins
  resources :enrolls do
    get "studentenroll"
  end
  resources :instructors
  resources :students do
    get "test"
  end
  resources :courses do
    get "wait"
    get "waitremove"
  end
  resources :users
  root 'home#index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "users#signup", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorized, only: [:index]

  def index
    @courses = Course.all
    @students = Student.all
    @instructors = Instructor.all
    if current_user
      @yourcourses = Course.where(instructoremail: current_user.email)
      # @students = Enroll.where(course_id:)
    end
    @courses = Course.all
    @students = Student.all
    @instructors = Instructor.all
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_courses.html.erb
<h1>Courses</h1>

<div id="courses" class="table-responsive">
  <table class="table table-hover table-sm table-bordered table-striped">
    <thead class="table-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Instructor Name</th>
      <th scope="col">Weekday 1</th>
      <th scope="col">Weekday 2</th>
      <th scope="col">Start time</th>
      <th scope="col">End time</th>
      <th scope="col">Course Code</th>
      <th scope="col">Capacity</th>
      <th scope="col">Room</th>
      <th scope="col">Status</th>
      <% if current_user.user_type == "student" %>
        <th scope="col">Enroll</th>
      <% else %>
        <th scope="col">Show</th>
      <%end %>
    </tr>
    </thead>
    <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td> <%= course.Name %> </td>
        <td> <%= course.Description %> </td>
        <td> <%= course.Instructor_Name %> </td>
        <td> <%= course.Weekday1 %> </td>
        <td> <%= course.Weekday2 %> </td>
        <td> <%= course.Start_Time.strftime('%H:%M') %> </td>
        <td> <%= course.End_Time.strftime('%H:%M') %> </td>
        <td> <%= course.Course_Code %> </td>
        <td> <%= course.Capacity %> </td>
        <td> <%= course.Room %> </td>
        <td> <%= course.Status %> </td>
        <% if current_user.user_type == "student" %>
          <td> <%= link_to "Enroll", new_enroll_path(:course_id => course.id, :student_id => current_user.id), {:class => "link-dark"}  %></td>
        <% else %>
          <td><%= link_to "Course Details", course, class: "btn btn-outline-dark" %></td>
        <%end %>
      </tr>
    <%end %>
    </tbody>
  </table>
</div>

<% if current_user.user_type == "admin" or  current_user.user_type == "instructor" %>
  <%= link_to "Add Course+", new_course_path, class: "btn btn-secondary" %>
<%end %>

app/views/home/_instructors.html.erb
<h1>Instructors</h1>

<div id="instructors" class="table-responsive">
  <table class="table table-hover table-sm table-bordered table-striped">
    <thead class="table-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Department</th>
      <th scope="col">Show</th>
    </tr>
    </thead>
    <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td> <%= instructor.Name %> </td>
        <td> <%= instructor.email %> </td>
        <td> <%= instructor.Department %> </td>
        <td><%= link_to "Instructor Details", instructor, class: "btn btn-outline-dark" %></td>
      </tr>
    <%end %>
    </tbody>
  </table>
</div>

<% if current_user.user_type == "admin" or  current_user.user_type == "instructor" %>
  <%= link_to "Add Instructor+", new_instructor_path, class: "btn btn-secondary"%>
<%end %>

app/views/home/_students.html.erb
<h1>Students</h1>

<div id="students" class="table-responsive">
  <table class="table table-hover table-sm table-bordered table-striped">
    <thead class="table-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Student ID</th>
      <th scope="col">Email</th>
      <th scope="col">Date of birth</th>
      <th scope="col">Phone number</th>
      <th scope="col">Major</th>
      <th scope="col">Show</th>
    </tr>
    </thead>
    <tbody>
    <% @students.each do |student| %>
      <tr class="table-row">
        <td> <%= student.Name %> </td>
        <td> <%= student.Student_ID %> </td>
        <td> <%= student.email %> </td>
        <td> <%= student.date_of_birth %> </td>
        <td> <%= student.Phone_Number %> </td>
        <td> <%= student.Major %> </td>
        <td><%= link_to "Student Details", student, class: "btn btn-outline-dark" %></td>
      </tr>
    <%end %>
    </tbody>
  </table>
</div>

<% if current_user.user_type == "admin" or  current_user.user_type == "instructor" %>
  <%= link_to "Add Student+", new_student_path, class: "btn btn-secondary"%>
<%end %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Enrollment Portal</h1>
<p>Manage course enrollment at the snap of your finger</p>
<% if current_user %>
  <% if current_user.user_type == "student" %>
    Logged in as <%= current_user.email %><br> <br>
    <%= link_to "All Courses", courses_path, {:class => "link-dark"} %><br> <br>
    <%= link_to "My Courses", enrolls_path, {:class => "link-dark"} %><br> <br>
    <%= link_to "Waitlisted Courses", waitlists_path, {:class => "link-dark"} %><br> <br>
    <%= link_to "Logout", logout_path, {:class => "link-dark"} %>
  <% elsif current_user.user_type == "instructor" %>
    Logged in as <%= current_user.email %><br>
    <%= link_to "New Course", new_course_path, {:class => "link-dark"} %> <br>
    <%= link_to "Your Courses", courses_path, {:class => "link-dark"} %><br>
    <%= link_to "Logout", logout_path, {:class => "link-dark"} %>
  <% else current_user.user_type == "admin" %>
    <div class="flex-box-right">
      <%= link_to "View Profile", admins_url, {:class => "link-dark"} %> &nbsp; &nbsp;
      <%= link_to "Logout", logout_path, {:class => "link-dark"} %>
    </div>
    Logged in as <%= current_user.email %><br>
    <%= render "courses", course: @courses %><br><br>
    <%= render "students", course: @students %><br><br>
    <%= render "instructors", course: @instructors %><br><br>
  <% end %>
<% else %>
  <%= link_to "Signup", signup_path, {:class => "link-dark"} %> or
  <%= link_to "Login", login_path, {:class => "link-dark"} %>
<% end %>