config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :admins
  resources :enrolls do
    get "studentenroll"
  end
  resources :instructors
  resources :students do
    get "test"
  end
  resources :courses do
    get "wait"
    get "waitremove"
  end
  resources :users
  root 'home#index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: "users#signup", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
    @yourcourses = Course.where(instructoremail: current_user.email)
    # if current_user.user_type == "instructor"
    #   e = Enroll.where(course_id: params[:course_id], student_id: params[:student_id]).pluck(:id)
    #   Enroll.delete(e)
    # end
  end

  def enrolled
    @students = Enroll.where(course_id:@course.id)
  end

  # GET /courses/1 or /courses/1.json
  def show
    @students = Enroll.where(course_id:@course.id)
    if @course.Capacity > 0
      @course.Status = "OPEN"
      @course.save
    elsif @course.Waitlist_Capacity > 0
      @course.Status = "WAITLIST"
      @course.save
    else
      @course.Status = "CLOSED"
      @course.save
    end
  end

  # GET /courses/new
  def new
    @course = Course.new
    inst = Instructor.where(email: current_user.email).pluck(:name)
    @instname = inst[0]
  end

  # GET /courses/1/edit
  def edit
  end
  def waitremove
    @students = Student.all
    if current_user.user_type != "student"
      @students = Waitlist.where(course_id:params[:course_id])
      @cid = params[:course_id]

    end
    w = Waitlist.where(course_id: params[:course_id], student_id: params[:student_id]).pluck(:id)
    Waitlist.delete(w)
    @course = Course.find(params[:course_id])

    @course.Waitlist_Capacity = @course.Waitlist_Capacity + 1

    @course.save

  end

  def wait
    @students = Student.all
    if current_user.user_type != "student"
      @students = Waitlist.where(course_id:params[:course_id])
      @cid = params[:course_id]

    end
  end
  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    if current_user.user_type == "instructor"
      @course.Instructor_Name = Instructor.where(email: current_user.email).pluck(:name)[0]
      @course.instructoremail = current_user.email
    end
    if @course.Capacity > 0
      @course.Status = "OPEN"
      @course.save
    elsif @course.Waitlist_Capacity > 0
      @course.Status = "WAITLIST"
      @course.save
    else
      @course.Status = "CLOSED"
      @course.save
    end
    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    if current_user.user_type == "instructor"
      e = Enroll.where(course_id: @course.id).pluck(:id)
      for i in e
        Enroll.delete(i)
      end
    end
    @course.destroy

    respond_to do |format|
      if current_user.user_type.eql?("admin")
        format.html { redirect_to root_url, notice: "Course was successfully destroyed." }
        format.json { head :no_content }
      else
        format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:Name, :Description, :Instructor_Name, :instructoremail, :Weekday1, :Weekday2, :Start_Time, :End_Time, :Course_Code, :Capacity, :Waitlist_Capacity, :Room, :Status)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p>
    <strong>Name:</strong>
    <%= course.Name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= course.Description %>
  </p>

  <p>
    <strong>Instructor name:</strong>
    <%= course.Instructor_Name %>
  </p>


  <p>
    <strong>Instructor email:</strong>
    <%= course.instructoremail %>
  </p>

  <p>
    <strong>Weekday1:</strong>
    <%= course.Weekday1 %>
  </p>

  <p>
    <strong>Weekday2:</strong>
    <%= course.Weekday2 %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= course.Start_Time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= course.End_Time %>
  </p>

  <p>
    <strong>Course code:</strong>
    <%= course.Course_Code %>
  </p>

  <p>
    <strong>Capacity:</strong>
    <%= course.Capacity %>
  </p>

  <p>
    <strong>Waitlist capacity:</strong>
    <%= course.Waitlist_Capacity %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= course.Room %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= course.Status %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
    <div>
      <%= form.label :Name, style: "display: block" %>
      <%= form.text_field :Name %>
    </div>

  <div>
    <%= form.label :Description, style: "display: block" %>
    <%= form.text_field :Description %>
  </div>

  <div>
    <%= form.label :Instructor_Name, style: "display: block" %>
    <% if current_user.user_type == "instructor" %>
      <%= form.text_field :Instructor_Name, placeholder:@instname, disabled: true %>
    <% end %>
    <% if current_user.user_type == "admin" %>
      <%= form.text_field :Instructor_Name %>
    <% end %>
  </div>

  <div>
    <%= form.label :Instructor_Email, style: "display: block" %>
    <% if current_user.user_type == "instructor" %>
      <%= form.text_field :instructoremail, placeholder: current_user.email, disabled: true %>
    <% end %>
    <% if current_user.user_type == "admin" %>
      <%= form.text_field :instructoremail %>
    <% end %>

  </div>

  <div>
    <%= form.label :Course_Code, style: "display: block" %>
    <%= form.text_field :Course_Code %>
  </div>

  <div>
    <%= form.label :Room, style: "display: block" %>
    <%= form.text_field :Room %>
  </div>

  <div>
    <%= form.label :Capacity, style: "display: block" %>
    <%= form.number_field :Capacity %>
  </div>

  <div>
    <%= form.label :Waitlist_Capacity, style: "display: block" %>
    <%= form.number_field :Waitlist_Capacity %>
  </div>

  <div>
    <%= form.label :Weekday1, style: "display: block" %>
    <%= form.select(:Weekday1, options_for_select([%w[Monday MON], %w[Tuesday TUE], %w[Wednesday WED], %w[Thursday THU], %w[Friday FRI]]), { include_blank: true}) %>
  </div>

  <div>
    <%= form.label :Weekday2, style: "display: block" %>
    <%= form.select(:Weekday2, options_for_select([%w[Monday MON], %w[Tuesday TUE], %w[Wednesday WED], %w[Thursday THU], %w[Friday FRI]]), { include_blank: true}) %>
  </div>

  <div>
    <%= form.label :Start_Time, style: "display: block" %>
    <%= form.time_field :Start_Time %>
  </div>

  <div>
    <%= form.label :End_Time, style: "display: block" %>
    <%= form.time_field :End_Time %>
  </div>

  <br>
  <div>
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course, {:class => "link-dark"}  %> |
  <%= link_to "Back to courses", courses_path, {:class => "link-dark"}  %>
</div>

app/views/courses/enrolled.html.erb
<% if current_user.user_type == "instructor" %>
  <p> Enrolled Students </p>
    <ol>
    <% @students.each do |stu| %>
        <li>
          <%= link_to student_path(stu.student_id), {:class => "link-dark"}  do %>
            <%= Student.where(:id => stu.student_id).pluck(:name).first %>
          <% end %>
        </li>
    <% end %>
  </ol>

  <%end %>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Courses</h1>

<div>
<% if current_user.user_type == "instructor" %>
<p> List of Your Courses </p><br>
    <ol>
      <% @yourcourses.each do |icourse| %>
          <li>
            <%= link_to course_path(icourse), {:class => "link-dark"}  do %>
              <%= icourse.Course_Code %>
            <% end %>
          </li>
      <% end %>
    </ol>
  <% end %>
</div>

<div id="courses">
<% if current_user.user_type != "instructor" %>
  <table class="table table-hover table-sm">
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Instructor Name</th>
      <th scope="col">Weekday 1</th>
      <th scope="col">Weekday 2</th>
      <th scope="col">Start time</th>
      <th scope="col">End time</th>
      <th scope="col">Course Code</th>
      <th scope="col">Capacity</th>
      <th scope="col">Waitlist Capacity</th>
      <th scope="col">Room</th>
      <th scope="col">Status</th>
      <% if current_user.user_type == "student" %>
        <th scope="col">Enrollment</th>
      <% else %>
        <th scope="col">Show</th>
      <%end %>
    </tr>
    </thead>
    <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td> <%= course.Name %> </td>
        <td> <%= course.Description %> </td>
        <td> <%= course.Instructor_Name %> </td>
        <td> <%= course.Weekday1 %> </td>
        <td> <%= course.Weekday2 %> </td>
        <td> <%= course.Start_Time.strftime('%H:%M') %> </td>
        <td> <%= course.End_Time.strftime('%H:%M') %> </td>
        <td> <%= course.Course_Code %> </td>
        <td> <%= course.Capacity %> </td>
        <td> <%= course.Waitlist_Capacity %></td>
        <td> <%= course.Room %> </td>
        <% if course.Capacity > 0 %>
         <td> <%= "OPEN" %> </td>
        <%elsif course.Waitlist_Capacity > 0 %>
          <td> <%= "WAITLIST" %> </td>
        <% else %>
          <td> <%= "CLOSED" %> </td>
        <%end %>
        <% if current_user.user_type == "student" %>
          <% if course.Capacity == 0 and course.Waitlist_Capacity > 0  %>
              <td> <%= link_to "Waitlist", new_waitlist_path(:course_id => course.id), {:class => "link-dark"} %></td>
            <%else %>
              <td> <%= link_to_if course.Capacity > 0,  "Enroll", new_enroll_path(:course_id => course.id), {:class => "link-dark"} %></td>
          <%end %>
        <% else %>
          <td><%= link_to "Show this course", course, class: "btn btn-secondary" %></td>
        <%end %>
      </tr>
    <%end %>
    </tbody>
  </table>
  <%end%>
</div>

<% if current_user.user_type == "admin"  %>
  <%= link_to "New course", new_course_path, {:class => "link-dark"} %>
<%end %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <% if current_user.user_type == "admin" %>
    <%= link_to "Back to Home", root_path, {:class => "link-dark"} %>
  <%else %>
    <%= link_to "Back to courses", courses_path, {:class => "link-dark"} %>
  <%end %>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>


<%= render @course %>

<div>
  <% if current_user.user_type == "student" %>

  <%else %>
    <div class="flex-box">
      <%= link_to "Edit this course", edit_course_path(@course), class: "btn btn-secondary" %> &nbsp; &nbsp;
      <%= button_to "Destroy this course", @course, method: :delete, class: "btn btn-secondary" %>
    </div>
  <%end %>
  <% if current_user.user_type != "student"%>
    <br><br>
    <div class="flex-box">
      <%= link_to "Enroll a student", new_enroll_path(:course_id => @course.id) , class: "btn btn-secondary" %>  &nbsp; &nbsp;
      <%= link_to "Enrolled Students", students_path(:course_id => @course.id), class: "btn btn-secondary" %>
      &nbsp;&nbsp;&nbsp;
      <%= link_to "Waitlist Students", course_wait_path(:course_id => @course.id), class: "btn btn-secondary" %>
  <%end %>
    </div>

  </br> </br>
    <% if current_user.user_type == "admin" %>
      <%= link_to "Back to Home", root_path, {:class => "link-dark"} %>
    <%else %>
      <%= link_to "Back to courses", courses_path,  {:class => "link-dark"} %>
    <%end %>



</div>

app/views/courses/wait.html.erb
<div>
<% if current_user.user_type != "student" %>
<p> Waitlist Students </p>
    <table class="table table-hover table-sm table-bordered table-striped">
    <thead class="table-dark">
    <tr>
        <th scope="col">Email</th>
        <th scope="col">Remove</th>
    </tr>
    </thead>
    <tbody>
    <% @students.each do |stu| %>
        <tr>
          <%= link_to student_path(stu.student_id, :course_id => @cid) do %>
            <td><%= Student.where(:id => stu.student_id).pluck(:email).first %></td>
            <td><%= link_to "Remove", course_waitremove_path(:student_id => stu.student_id, :course_id => @cid) %></td>
          <% end %>
          <tr>
        
    <% end %>
    </tbody>
    </table>
  
<% end %>

</div>

app/views/courses/waitremove.html.erb
<div>
<% if current_user.user_type != "student" %>
<p> Waitlist Students </p>
    <table class="table table-hover table-sm table-bordered table-striped">
    <thead class="table-dark">
    <tr>
        <th scope="col">Email</th>
        <th scope="col">Remove</th>
    </tr>
    </thead>
    <tbody>
    <% @students.each do |stu| %>
        <tr>
          <%= link_to student_path(stu.student_id, :course_id => @cid) do %>
            <td><%= Student.where(:id => stu.student_id).pluck(:email).first %></td>
            <td><%= link_to "Remove", course_waitremove_path(:student_id => stu.student_id, :course_id => @cid) %></td>
          <% end %>
          <tr>
        
    <% end %>
    </tbody>
    </table>
  
<% end %>

</div>